repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.28.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black
          - --src=src

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
          - --skip-string-normalization

  - repo: https://github.com/python-poetry/poetry
    rev: '1.3.2'
    hooks:
      - id: poetry-check
      - id: poetry-lock
        language_version: python3.10
        args:
          - --check
      - id: poetry-export
        args:
          - --format=requirements.txt
          - --output=requirements.txt
          - --without-hashes
          - --without-urls
